FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3.6 \
    git \
    nodejs \
    npm \
    python3-pip

RUN pip3 install -U pip setuptools

RUN mkdir /mindlogger-backend
WORKDIR /mindlogger-backend
#copy and install requirements early to allow faster rebuilds as these layers will be cached 
COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
RUN pip3 install -e .

# See http://click.pocoo.org/5/python3/#python-3-surrogate-handling for more detail on
# why this is necessary.
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN girderformindlogger build --dev
CMD [ "girderformindlogger","serve" ]