version: '3'

services:
  mongo:
    image: mongo:4-bionic
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - "mongovolume:/data/db"
      # - "./mongo/mongod.conf:/etc/mongod.conf":ro
      # - "./mongo/mongodb.pem:/etc/mongod.pem":ro  
    environment:
      MONGO_INITDB_DATABASE: girderformindlogger
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    command: ["--auth"]      

  girderformindlogger:
    image: barry8000/ml-backend:test3
    # volumes:
    #   - "./:/girderformindlogger"
    ports:
      - "8081:8081"
    environment:
      GIRDER_PORT: 8081
      GIRDER_MONGO_URI: http://localhost:8081
      GIRDER_TEST_DB: girder-test
      MONGODB_URI: mongodb://mongouser:mongopass@mongo:27017
      DB_NAME: girderformindlogger
      ACCESS_KEY_ID: 1
      SECRET_ACCESS_KEY: 1
      HTTP_HOST: localhost
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    # env_file:
    #   - ./girderformindlogger/.env.local
    command: ["girderformindlogger", "serve","--host","0.0.0.0","--database","mongodb://mongouser:mongopass@mongo:27017"]

volumes:
  mongovolume:
      driver: local